---
- hosts: all
  sudo: true
  tasks:
  - name: update apt
    apt: update_cache=yes
  - include: common/tasks/tools.yml
  - include: dev/tasks/apache.yml
  - include: dev/tasks/java.yml
  - include: dev/tasks/mysql.yml
  - include: dev/tasks/tomcat.yml
